create schema semeru2;
use semeru2;
CREATE USER 'semeru2'@'%' IDENTIFIED BY 'UeAHjOO84PuaJib3chLbAL5v';
GRANT INSERT, UPDATE, DELETE, SELECT ON semeru2.* TO 'semeru2'@'%';

create table credentials(
    account_id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    email_address VARCHAR(64) NOT NULL UNIQUE,
    password VARCHAR(64) NOT NULL,
    salt VARCHAR(8) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    modified_at TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 AUTO_INCREMENT=100000;